export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_RESET = 'CART_RESET';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_REMOVE_SHIPPING_ADDRESS = 'CART_REMOVE_SHIPPING_ADDRESS';

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_REMOVE_PAYMENT_METHOD = 'CART_REMOVE_PAYMENT_METHOD';
export const CART_SAVE_CHECKOUT_BUTTON_SELECTED =
	'CART_SAVE_CHECKOUT_BUTTON_SELECTED';

export const CART_REDIRECT_TO = 'CART_REDIRECT_TO';
